// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvG0Pn2LIeEu_hDLmb7_lgmX1wWkxUvNA',
    appId: '1:797556281437:web:adf0be7a16f622c952bdb4',
    messagingSenderId: '797556281437',
    projectId: 'harta-catan',
    authDomain: 'harta-catan.firebaseapp.com',
    storageBucket: 'harta-catan.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMXpDmYq915snEasH48pHUuBYbOi86fuQ',
    appId: '1:797556281437:android:962a17300be0fb7f52bdb4',
    messagingSenderId: '797556281437',
    projectId: 'harta-catan',
    storageBucket: 'harta-catan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIuBG27x0DTbHmZ6zoDMCm_a3035vNmrA',
    appId: '1:797556281437:ios:5573a92e3f90e12352bdb4',
    messagingSenderId: '797556281437',
    projectId: 'harta-catan',
    storageBucket: 'harta-catan.firebasestorage.app',
    iosBundleId: 'com.example.hartaCatan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIuBG27x0DTbHmZ6zoDMCm_a3035vNmrA',
    appId: '1:797556281437:ios:5573a92e3f90e12352bdb4',
    messagingSenderId: '797556281437',
    projectId: 'harta-catan',
    storageBucket: 'harta-catan.firebasestorage.app',
    iosBundleId: 'com.example.hartaCatan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvG0Pn2LIeEu_hDLmb7_lgmX1wWkxUvNA',
    appId: '1:797556281437:web:60a7b68a18b9626252bdb4',
    messagingSenderId: '797556281437',
    projectId: 'harta-catan',
    authDomain: 'harta-catan.firebaseapp.com',
    storageBucket: 'harta-catan.firebasestorage.app',
  );
}
